"""Export the guide template as readable Markdown using only the standard library."""

import re
from html.parser import HTMLParser
from pathlib import Path


class GuideParser(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.in_article = False
        self.blocks = []
        self.current_tag = None
        self.current_text = []

    def handle_starttag(self, tag, attrs):
        if tag == "article":
            self.in_article = True
        if not self.in_article:
            return
        if tag in ("h1", "h2", "subtitle", "p", "li"):
            self.current_tag = tag
            self.current_text = []
        elif tag == "strong":
            self.current_text.append("**")
        elif tag == "img":
            source = dict(attrs).get("src", "")
            match = re.fullmatch(
                r"\{\{\s*url_for\('static', filename='([^']+)'\)\s*\}\}",
                source,
            )
            if not match:
                raise ValueError(f"Unsupported image source: {source}")
            self.blocks.append(f"![](../api/static/{match.group(1)})")

    def handle_data(self, data):
        if self.in_article and self.current_tag:
            self.current_text.append(data)

    def handle_endtag(self, tag):
        if tag == "article":
            self.in_article = False
        if not self.in_article:
            return
        if tag == "strong":
            self.current_text.append("**")
        elif tag == self.current_tag:
            text = re.sub(r"\s+", " ", "".join(self.current_text)).strip()
            prefix = {"h1": "# ", "h2": "## ", "li": "- "}.get(tag, "")
            self.blocks.append(prefix + text)
            self.current_tag = None
            self.current_text = []


def export_guide(source, destination):
    parser = GuideParser()
    parser.feed(source.read_text(encoding="utf-8"))
    parser.close()
    if not parser.blocks:
        raise ValueError("No guide content found")
    notice = (
        "<!-- Generated by scripts/export_webpage_content.py from "
        "api/templates/content.html. Do not edit directly. -->\n\n"
        "[Back to the project overview](../README.md)\n\n"
        "This is the complete guide text and its illustrations, exported from "
        "the webpage source. Wording and punctuation are unchanged; layout "
        "and extra whitespace differ.\n\n"
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(notice + "\n\n".join(parser.blocks) + "\n", encoding="utf-8")


def main():
    root = Path(__file__).resolve().parents[1]
    export_guide(root / "api/templates/content.html", root / "docs/webpage-content.md")


if __name__ == "__main__":
    main()
